Invalidate and read snoop transactions
planvtech/axi pull request #14
Opened 2022-11-04 12:51 UTC by suppamax

2022-11-06 10:45 UTC, BasitSajjad commented on src/snoop_test.sv
> +  class snoop_rand_master #(
Role of master and slave are reversed. Although it might not affect the functionality.

2022-11-06 10:59 UTC, BasitSajjad commented on src/snoop_test.sv
> +        drv.recv_cd(ace_cd_beat);
We will able to receive single-beat (64-bit) data from snooping master. What if we need burst data as discussed earlier i.e., 128-bit (to read entire cache line).

2022-11-06 11:17 UTC, BasitSajjad commented on src/snoop_test.sv
> +      virtual ACE_BUS_DV #(
I think it should be snoop_bus_dv

2022-11-06 11:20 UTC, BasitSajjad commented on src/snoop_test.sv
> +        ace_ac_queue.push_back(ace_ac_beat);
Do we need queue for AC channel. (just asking for clarity).

2022-11-06 12:10 UTC, BasitSajjad requested changes
There are few suggestions and a single modification. Please review them.

2022-11-06 18:40 UTC, suppamax commented on src/snoop_test.sv
> +  class snoop_rand_master #(
No
The snoop master generates requests over the AC channel and gets responses over CR and CD
I agree that and ACE slave is a snoop master, which might be confusing.
But having a snoop master which doesn't initiates snoop requests seems illogical to me

2022-11-06 18:45 UTC, suppamax commented on src/snoop_test.sv
> +        drv.recv_cd(ace_cd_beat);
Good point
this might affect the implementation of read requests here.
A snoop request doesn't have a data size or length. I would say the snoop slave has to sent all words of a line (in our case 2x64 bits) and use CD.last to signal the end of the transmission. Or send directly 1x128 bits

2022-11-06 18:47 UTC, suppamax commented on src/snoop_test.sv
> +      virtual ACE_BUS_DV #(
Right

2022-11-06 18:50 UTC, suppamax commented on src/snoop_test.sv
> +        ace_ac_queue.push_back(ace_ac_beat);
I am honestly not 100% sure this is necessary.

2022-11-07 03:39 UTC, BasitSajjad commented on src/snoop_test.sv
> +  class snoop_rand_master #(
Could not agree more. It makes sense.

2022-11-07 03:41 UTC, BasitSajjad commented on src/snoop_test.sv
> +      virtual ACE_BUS_DV #(
Please change the parameters as well i.e., AXI_ADDR_WIDTH to SNOOP_ADDR_WIDTH

2022-11-07 03:49 UTC, BasitSajjad commented on src/snoop_test.sv
>          .AXI_DATA_WIDTH(DW)
parameters needs to be changed as well.

2022-11-07 06:33 UTC, suppamax commented on src/snoop_test.sv
> +      virtual ACE_BUS_DV #(
right - done

2022-11-07 06:33 UTC, suppamax commented on src/snoop_test.sv
>          .AXI_DATA_WIDTH(DW)
done

2022-11-07 06:53 UTC, BasitSajjad approved these changes

2022-11-07 07:06 UTC, merged

2022-11-07 07:09 UTC, suppamax commented
Thanks Abdul!